"""
FinSight — Agent State
=======================
The shared state object that flows through every node in the LangGraph pipeline.

Think of it as the whiteboard in the middle of the meeting room.
Every agent reads from it and writes to it.
The state starts with just the user's query and gets progressively
filled in as it passes through each agent.

Flow:
    User query → Planner fills 'plan' → Retriever fills 'chunks' 
    → Synthesizer fills 'answer' and 'sources'
"""

from typing import Annotated
from pydantic import BaseModel, Field
import operator

class AgentState(BaseModel):
    """
    Shared state passed between all agents in the pipeline.
    
    Each field represents one piece of information that agents
    either need to read or are responsible for writing.
    """

    # ── Input ──────────────────────────────────────────
    # The original question from the user. Set at the very start, never modified by any agent.
    query: str = Field(description="The original user question")

    # ── Planner output ─────────────────────────────────
    # The Planner breaks the query into a list of search sub-tasks.
    # Example: ["search NVDA for AI risks", "search NVDA for competition"]
    # Starts empty, filled by the Planner agent.
    plan: list[str] = Field(
        default_factory=list,
        description="List of search sub-tasks generated by the Planner"
    )

    # ── Retriever output ───────────────────────────────
    # The chunks retrieved from Qdrant for each sub-task. Each chunk is a dict with text, score, ticker, filing_date etc.
    # Why Annotated[list, operator.add]?
    # In LangGraph, if multiple nodes write to the same field, the default behaviour is to overwrite. But for chunks we want to ACCUMULATE — each retrieval adds to the list, not replaces it.
    # operator.add tells LangGraph to append new chunks to existing ones instead of overwriting the existing ones.
    chunks: list[dict] = Field(
    default_factory=list,
    description="Retrieved chunks from Qdrant and/or web search"
    )

    # ── Synthesizer output ─────────────────────────────
    # The final answer written by the Synthesizer agent.
    # Starts empty, filled at the end of the pipeline.
    answer: str = Field(
        default="",
        description="Final synthesized answer"
    )

    # ── Sources ────────────────────────────────────────
    # List of source references for the answer.
    # Example: ["Apple 10-K 2024-11-01", "NVIDIA 10-K 2026-02-25"]
    sources: list[str] = Field(
        default_factory=list,
        description="Source references used to generate the answer"
    )

    # ── Evaluator output ───────────────────────────────
    # A quality score between 0 and 1 assigned by the Evaluator agent.
    # If below EVAL_SCORE_THRESHOLD, the pipeline retries.
    eval_score: float = Field(
        default=0.0,
        description="Answer quality score from the Evaluator agent (0-1)"
    )

    # ── Retry tracking ─────────────────────────────────
    # Counts how many times the pipeline has retried.
    # Prevents infinite retry loops.
    retry_count: int = Field(
        default=0,
        description="Number of times the pipeline has retried"
    )

    # Critic Agent fields
    context_sufficient: bool = Field(
        default=True,
        description="Whether retrieved context is sufficient to answer the query"
    )
    critic_reason: str = Field(
        default="",
        description="Critic's explanation of its sufficiency judgment"
    )
    
    # Router fields
    route: str = Field(
        default="retriever",
        description="Routing decision: retriever, web_search, or both"
    )